/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as appAboutRouteImport } from './routes/(app)/about'
import { Route as appDocRouteRouteImport } from './routes/(app)/doc/route'
import { Route as ApiV1IndexRouteImport } from './routes/api/v1/index'
import { Route as appDocIndexRouteImport } from './routes/(app)/doc/index'
import { Route as ApiV1TopLangsRouteImport } from './routes/api/v1/top-langs'
import { Route as ApiV1PinRouteImport } from './routes/api/v1/pin'
import { Route as ApiV1GistRouteImport } from './routes/api/v1/gist'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as appStatsUsernameRouteImport } from './routes/(app)/stats/$username'
import { Route as appDocTopLangsRouteImport } from './routes/(app)/doc/top-langs'
import { Route as appDocStatsRouteImport } from './routes/(app)/doc/stats'
import { Route as appDocPinRouteImport } from './routes/(app)/doc/pin'
import { Route as appDocGistRouteImport } from './routes/(app)/doc/gist'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const appAboutRoute = appAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => appRouteRoute,
} as any)
const appDocRouteRoute = appDocRouteRouteImport.update({
  id: '/doc',
  path: '/doc',
  getParentRoute: () => appRouteRoute,
} as any)
const ApiV1IndexRoute = ApiV1IndexRouteImport.update({
  id: '/api/v1/',
  path: '/api/v1/',
  getParentRoute: () => rootRouteImport,
} as any)
const appDocIndexRoute = appDocIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appDocRouteRoute,
} as any)
const ApiV1TopLangsRoute = ApiV1TopLangsRouteImport.update({
  id: '/api/v1/top-langs',
  path: '/api/v1/top-langs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PinRoute = ApiV1PinRouteImport.update({
  id: '/api/v1/pin',
  path: '/api/v1/pin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1GistRoute = ApiV1GistRouteImport.update({
  id: '/api/v1/gist',
  path: '/api/v1/gist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const appStatsUsernameRoute = appStatsUsernameRouteImport.update({
  id: '/stats/$username',
  path: '/stats/$username',
  getParentRoute: () => appRouteRoute,
} as any)
const appDocTopLangsRoute = appDocTopLangsRouteImport.update({
  id: '/top-langs',
  path: '/top-langs',
  getParentRoute: () => appDocRouteRoute,
} as any)
const appDocStatsRoute = appDocStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => appDocRouteRoute,
} as any)
const appDocPinRoute = appDocPinRouteImport.update({
  id: '/pin',
  path: '/pin',
  getParentRoute: () => appDocRouteRoute,
} as any)
const appDocGistRoute = appDocGistRouteImport.update({
  id: '/gist',
  path: '/gist',
  getParentRoute: () => appDocRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/doc': typeof appDocRouteRouteWithChildren
  '/about': typeof appAboutRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/': typeof appIndexRoute
  '/doc/gist': typeof appDocGistRoute
  '/doc/pin': typeof appDocPinRoute
  '/doc/stats': typeof appDocStatsRoute
  '/doc/top-langs': typeof appDocTopLangsRoute
  '/stats/$username': typeof appStatsUsernameRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/v1/gist': typeof ApiV1GistRoute
  '/api/v1/pin': typeof ApiV1PinRoute
  '/api/v1/top-langs': typeof ApiV1TopLangsRoute
  '/doc/': typeof appDocIndexRoute
  '/api/v1': typeof ApiV1IndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof appAboutRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/': typeof appIndexRoute
  '/doc/gist': typeof appDocGistRoute
  '/doc/pin': typeof appDocPinRoute
  '/doc/stats': typeof appDocStatsRoute
  '/doc/top-langs': typeof appDocTopLangsRoute
  '/stats/$username': typeof appStatsUsernameRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/v1/gist': typeof ApiV1GistRoute
  '/api/v1/pin': typeof ApiV1PinRoute
  '/api/v1/top-langs': typeof ApiV1TopLangsRoute
  '/doc': typeof appDocIndexRoute
  '/api/v1': typeof ApiV1IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/doc': typeof appDocRouteRouteWithChildren
  '/(app)/about': typeof appAboutRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/doc/gist': typeof appDocGistRoute
  '/(app)/doc/pin': typeof appDocPinRoute
  '/(app)/doc/stats': typeof appDocStatsRoute
  '/(app)/doc/top-langs': typeof appDocTopLangsRoute
  '/(app)/stats/$username': typeof appStatsUsernameRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/v1/gist': typeof ApiV1GistRoute
  '/api/v1/pin': typeof ApiV1PinRoute
  '/api/v1/top-langs': typeof ApiV1TopLangsRoute
  '/(app)/doc/': typeof appDocIndexRoute
  '/api/v1/': typeof ApiV1IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/doc'
    | '/about'
    | '/sitemap/xml'
    | '/'
    | '/doc/gist'
    | '/doc/pin'
    | '/doc/stats'
    | '/doc/top-langs'
    | '/stats/$username'
    | '/api/rpc/$'
    | '/api/v1/gist'
    | '/api/v1/pin'
    | '/api/v1/top-langs'
    | '/doc/'
    | '/api/v1'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/sitemap/xml'
    | '/'
    | '/doc/gist'
    | '/doc/pin'
    | '/doc/stats'
    | '/doc/top-langs'
    | '/stats/$username'
    | '/api/rpc/$'
    | '/api/v1/gist'
    | '/api/v1/pin'
    | '/api/v1/top-langs'
    | '/doc'
    | '/api/v1'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/doc'
    | '/(app)/about'
    | '/sitemap/xml'
    | '/(app)/'
    | '/(app)/doc/gist'
    | '/(app)/doc/pin'
    | '/(app)/doc/stats'
    | '/(app)/doc/top-langs'
    | '/(app)/stats/$username'
    | '/api/rpc/$'
    | '/api/v1/gist'
    | '/api/v1/pin'
    | '/api/v1/top-langs'
    | '/(app)/doc/'
    | '/api/v1/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  SitemapXmlRoute: typeof SitemapXmlRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ApiV1GistRoute: typeof ApiV1GistRoute
  ApiV1PinRoute: typeof ApiV1PinRoute
  ApiV1TopLangsRoute: typeof ApiV1TopLangsRoute
  ApiV1IndexRoute: typeof ApiV1IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/about': {
      id: '/(app)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof appAboutRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/doc': {
      id: '/(app)/doc'
      path: '/doc'
      fullPath: '/doc'
      preLoaderRoute: typeof appDocRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/api/v1/': {
      id: '/api/v1/'
      path: '/api/v1'
      fullPath: '/api/v1'
      preLoaderRoute: typeof ApiV1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/doc/': {
      id: '/(app)/doc/'
      path: '/'
      fullPath: '/doc/'
      preLoaderRoute: typeof appDocIndexRouteImport
      parentRoute: typeof appDocRouteRoute
    }
    '/api/v1/top-langs': {
      id: '/api/v1/top-langs'
      path: '/api/v1/top-langs'
      fullPath: '/api/v1/top-langs'
      preLoaderRoute: typeof ApiV1TopLangsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/pin': {
      id: '/api/v1/pin'
      path: '/api/v1/pin'
      fullPath: '/api/v1/pin'
      preLoaderRoute: typeof ApiV1PinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/gist': {
      id: '/api/v1/gist'
      path: '/api/v1/gist'
      fullPath: '/api/v1/gist'
      preLoaderRoute: typeof ApiV1GistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/stats/$username': {
      id: '/(app)/stats/$username'
      path: '/stats/$username'
      fullPath: '/stats/$username'
      preLoaderRoute: typeof appStatsUsernameRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/doc/top-langs': {
      id: '/(app)/doc/top-langs'
      path: '/top-langs'
      fullPath: '/doc/top-langs'
      preLoaderRoute: typeof appDocTopLangsRouteImport
      parentRoute: typeof appDocRouteRoute
    }
    '/(app)/doc/stats': {
      id: '/(app)/doc/stats'
      path: '/stats'
      fullPath: '/doc/stats'
      preLoaderRoute: typeof appDocStatsRouteImport
      parentRoute: typeof appDocRouteRoute
    }
    '/(app)/doc/pin': {
      id: '/(app)/doc/pin'
      path: '/pin'
      fullPath: '/doc/pin'
      preLoaderRoute: typeof appDocPinRouteImport
      parentRoute: typeof appDocRouteRoute
    }
    '/(app)/doc/gist': {
      id: '/(app)/doc/gist'
      path: '/gist'
      fullPath: '/doc/gist'
      preLoaderRoute: typeof appDocGistRouteImport
      parentRoute: typeof appDocRouteRoute
    }
  }
}

interface appDocRouteRouteChildren {
  appDocGistRoute: typeof appDocGistRoute
  appDocPinRoute: typeof appDocPinRoute
  appDocStatsRoute: typeof appDocStatsRoute
  appDocTopLangsRoute: typeof appDocTopLangsRoute
  appDocIndexRoute: typeof appDocIndexRoute
}

const appDocRouteRouteChildren: appDocRouteRouteChildren = {
  appDocGistRoute: appDocGistRoute,
  appDocPinRoute: appDocPinRoute,
  appDocStatsRoute: appDocStatsRoute,
  appDocTopLangsRoute: appDocTopLangsRoute,
  appDocIndexRoute: appDocIndexRoute,
}

const appDocRouteRouteWithChildren = appDocRouteRoute._addFileChildren(
  appDocRouteRouteChildren,
)

interface appRouteRouteChildren {
  appDocRouteRoute: typeof appDocRouteRouteWithChildren
  appAboutRoute: typeof appAboutRoute
  appIndexRoute: typeof appIndexRoute
  appStatsUsernameRoute: typeof appStatsUsernameRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appDocRouteRoute: appDocRouteRouteWithChildren,
  appAboutRoute: appAboutRoute,
  appIndexRoute: appIndexRoute,
  appStatsUsernameRoute: appStatsUsernameRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  SitemapXmlRoute: SitemapXmlRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiV1GistRoute: ApiV1GistRoute,
  ApiV1PinRoute: ApiV1PinRoute,
  ApiV1TopLangsRoute: ApiV1TopLangsRoute,
  ApiV1IndexRoute: ApiV1IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
